# Generated by Django 3.1.4 on 2021-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barplot',
            name='capsize',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barplot',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barplot',
            name='errcolor',
            field=models.CharField(blank=True, default='0.26', max_length=200),
        ),
        migrations.AddField(
            model_name='barplot',
            name='errwidth',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barplot',
            name='estimator',
            field=models.CharField(blank=True, choices=[('mean', 'mean'), ('median', 'median')], default='mean', max_length=200),
        ),
        migrations.AddField(
            model_name='barplot',
            name='hue',
            field=models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barplot',
            name='n_boot',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barplot',
            name='saturation',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barplot',
            name='y',
            field=models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='barplot',
            name='x',
            field=models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
    ]
