# Generated by Django 3.1.4 on 2021-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0002_auto_20210214_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barplot',
            name='n_boot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
