# Generated by Django 3.1.4 on 2021-02-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0003_auto_20210214_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarPlot',
            new_name='BarPlotModel',
        ),
    ]
