# Generated by Django 3.1.4 on 2021-02-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0008_auto_20210223_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxPlotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('y', models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('hue', models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('estimator', models.CharField(choices=[('mean', 'mean'), ('median', 'median')], default='none', max_length=200)),
                ('saturation', models.FloatField(blank=True, null=True)),
                ('palette', models.CharField(blank=True, choices=[('rocket', 'rocket'), ('mako', 'mako'), ('flare', 'flare'), ('crest', 'crest'), ('magma', 'magma'), ('viridis', 'viridis'), ('icefire', 'icefire'), ('inferno', 'inferno'), ('hot', 'hot')], max_length=200, null=True)),
                ('dodge', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountPlotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('y', models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('hue', models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('estimator', models.CharField(choices=[('mean', 'mean'), ('median', 'median')], default='none', max_length=200)),
                ('saturation', models.FloatField(blank=True, null=True)),
                ('palette', models.CharField(blank=True, choices=[('rocket', 'rocket'), ('mako', 'mako'), ('flare', 'flare'), ('crest', 'crest'), ('magma', 'magma'), ('viridis', 'viridis'), ('icefire', 'icefire'), ('inferno', 'inferno'), ('hot', 'hot')], max_length=200, null=True)),
                ('dodge', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistogramPlotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('y', models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('hue', models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True)),
                ('palette', models.CharField(blank=True, choices=[('rocket', 'rocket'), ('mako', 'mako'), ('flare', 'flare'), ('crest', 'crest'), ('magma', 'magma'), ('viridis', 'viridis'), ('icefire', 'icefire'), ('inferno', 'inferno'), ('hot', 'hot')], max_length=200, null=True)),
                ('legend', models.CharField(choices=[('auto', 'auto'), ('brief', 'brief'), ('full', 'full'), (False, False)], default='auto', max_length=200)),
                ('fillit', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=200, null=True)),
                ('stat', models.CharField(choices=[('count', 'count'), ('frequency', 'frequency'), ('density', 'density'), ('probability', 'probability')], max_length=200, null=True)),
                ('multiple', models.CharField(choices=[('layer', 'layer'), ('dodge', 'dodge'), ('stack', 'stack'), ('fill', 'fill')], max_length=200, null=True)),
                ('element', models.CharField(choices=[('bar', 'bar'), ('step', 'step'), ('poly', 'poly')], max_length=200, null=True)),
            ],
        ),
    ]
