# Generated by Django 3.1.4 on 2021-02-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0009_boxplotmodel_countplotmodel_histogramplotmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barplotmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='barplotmodel',
            name='name',
            field=models.CharField(default='Bar Plot', max_length=200, primary_key=True, serialize=False),
        ),
    ]
