# Generated by Django 3.1.4 on 2021-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0010_auto_20210225_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barplotmodel',
            name='saturation',
            field=models.FloatField(blank=True, default='0.75', null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='style',
            field=models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
    ]
