# Generated by Django 3.1.4 on 2021-02-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0011_auto_20210226_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barplotmodel',
            name='n_boot',
            field=models.IntegerField(default=1000),
        ),
    ]
