# Generated by Django 3.1.4 on 2021-02-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0012_auto_20210226_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barplotmodel',
            name='saturation',
            field=models.FloatField(blank=True, default=0.75, null=True),
        ),
    ]
