# Generated by Django 3.1.4 on 2021-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0016_auto_20210228_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='n_boot',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='x',
            field=models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], default='color', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='y',
            field=models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], default='price', max_length=200, null=True),
        ),
    ]
