# Generated by Django 3.1.4 on 2021-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0018_auto_20210228_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countplotmodel',
            name='dodge',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='style',
            field=models.CharField(blank=True, choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='name',
            field=models.CharField(default='Scatter Plot', max_length=200, primary_key=True, serialize=False),
        ),
    ]
