# Generated by Django 3.1.4 on 2021-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0019_auto_20210301_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxplotmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='countplotmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='histogramplotmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lineplotmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='boxplotmodel',
            name='name',
            field=models.CharField(default='Box Plot', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='countplotmodel',
            name='name',
            field=models.CharField(default='Count Plot', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='histogramplotmodel',
            name='name',
            field=models.CharField(default='Histogram', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lineplotmodel',
            name='name',
            field=models.CharField(default='Line Plot', max_length=200, primary_key=True, serialize=False),
        ),
    ]
