# Generated by Django 3.1.4 on 2021-03-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0020_auto_20210301_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineplotmodel',
            name='n_boot',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
