# Generated by Django 3.1.4 on 2021-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0022_auto_20210301_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countplotmodel',
            name='y',
        ),
        migrations.AlterField(
            model_name='boxplotmodel',
            name='dodge',
            field=models.CharField(choices=[('True', True), ('False', False)], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countplotmodel',
            name='dodge',
            field=models.CharField(choices=[('True', True), ('False', False)], default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='histogramplotmodel',
            name='fillit',
            field=models.CharField(choices=[('True', True), ('False', False)], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='sort',
            field=models.CharField(choices=[('True', True), ('False', False)], default='False', max_length=200),
        ),
    ]
