# Generated by Django 3.1.4 on 2021-03-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0023_auto_20210302_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histogramplotmodel',
            old_name='fillit',
            new_name='fill',
        ),
        migrations.AddField(
            model_name='histogramplotmodel',
            name='bins',
            field=models.CharField(default='auto', max_length=200),
        ),
        migrations.AddField(
            model_name='histogramplotmodel',
            name='binwidth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='histogramplotmodel',
            name='discrete',
            field=models.CharField(choices=[('True', True), ('False', False)], default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='histogramplotmodel',
            name='kde',
            field=models.CharField(choices=[('True', True), ('False', False)], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='histogramplotmodel',
            name='stat',
            field=models.CharField(choices=[('count', 'count'), ('frequency', 'frequency'), ('density', 'density'), ('probability', 'probability')], default='count', max_length=200, null=True),
        ),
    ]
