# Generated by Django 3.1.4 on 2021-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0026_auto_20210303_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxplotmodel',
            name='fliersize',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='boxplotmodel',
            name='linewidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boxplotmodel',
            name='width',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='boxplotmodel',
            name='saturation',
            field=models.FloatField(default=0.75),
        ),
    ]
