# Generated by Django 3.1.4 on 2021-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0028_auto_20210304_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxplotmodel',
            name='x',
            field=models.CharField(choices=[('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], default='cut', max_length=200, null=True),
        ),
    ]
