# Generated by Django 3.1.4 on 2021-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0034_auto_20210420_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='histogramplotmodel',
            name='log_scale',
            field=models.CharField(choices=[('True', True), ('False', False)], default=False, max_length=200),
        ),
    ]
