# Generated by Django 3.1.4 on 2021-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0035_histogramplotmodel_log_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barplotmodel',
            name='hue',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='barplotmodel',
            name='x',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='barplotmodel',
            name='y',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boxplotmodel',
            name='hue',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boxplotmodel',
            name='x',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boxplotmodel',
            name='y',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countplotmodel',
            name='hue',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countplotmodel',
            name='x',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='histogramplotmodel',
            name='hue',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='histogramplotmodel',
            name='legend',
            field=models.CharField(choices=[('auto', 'auto'), ('brief', 'brief'), ('full', 'full')], default='auto', max_length=200),
        ),
        migrations.AlterField(
            model_name='histogramplotmodel',
            name='x',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='hue',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='legend',
            field=models.CharField(choices=[('auto', 'auto'), ('brief', 'brief'), ('full', 'full')], default='auto', max_length=200),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='style',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='x',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineplotmodel',
            name='y',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='hue',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='legend',
            field=models.CharField(choices=[('auto', 'auto'), ('brief', 'brief'), ('full', 'full')], default='auto', max_length=200),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='style',
            field=models.CharField(blank=True, choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='x',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scatterplotmodel',
            name='y',
            field=models.CharField(choices=[('Unnamed: 0', 'Unnamed: 0'), ('carat', 'carat'), ('cut', 'cut'), ('color', 'color'), ('clarity', 'clarity'), ('depth', 'depth'), ('table', 'table'), ('price', 'price'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=200, null=True),
        ),
    ]
